#!/usr/bin/env python3
"""Remove runtime Skill mirrors generated by older infrastructure scaffolds."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from pathlib import Path

RUNTIME_ROOTS = (
    Path(".claude/skills"),
    Path(".agents/skills"),
    Path(".codebuddy/skills"),
    Path(".workbuddy/skills"),
)
MANIFEST = Path(".agent-infra/runtime-skill-mirrors.json")
SYNC_SCRIPT = Path("scripts/agent-skills/sync_runtime_skills.py")
BEGIN = "# BEGIN donald-agent-infrastructure generated"
END = "# END donald-agent-infrastructure generated"
LEGACY_IGNORES = {*(f"{path.as_posix()}/" for path in RUNTIME_ROOTS), ".agent-infra/"}


def tree_digest(root: Path) -> str:
    digest = hashlib.sha256(b"donald-agent-infrastructure-tree-v1\0")
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix()):
        relative = path.relative_to(root).as_posix().encode()
        if path.is_symlink():
            digest.update(b"L\0" + relative + b"\0" + os.readlink(path).encode() + b"\0")
        elif path.is_dir():
            digest.update(b"D\0" + relative + b"\0")
        elif path.is_file():
            digest.update(b"F\0" + relative + b"\0" + path.read_bytes() + b"\0")
    return digest.hexdigest()


def load_entries(repo: Path) -> list[dict[str, str]]:
    path = repo / MANIFEST
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid legacy manifest: {exc}") from exc
    if data.get("version") != 1 or not isinstance(data.get("mirrors"), list):
        raise ValueError("unsupported legacy manifest")
    return data["mirrors"]


def owned_target(repo: Path, entry: dict[str, str]) -> tuple[Path, str] | None:
    required = {"target", "source", "mode", "digest"}
    if not isinstance(entry, dict) or not required.issubset(entry):
        raise ValueError("malformed legacy manifest entry")
    if any(not isinstance(entry[key], str) for key in required):
        raise ValueError("malformed legacy manifest entry")
    target = Path(os.path.abspath(repo / entry["target"]))
    source = Path(os.path.abspath(repo / entry["source"]))
    allowed = {Path(os.path.abspath(repo / root)) for root in RUNTIME_ROOTS}
    try:
        source.relative_to(Path(os.path.abspath(repo / "skills")))
    except ValueError as exc:
        raise ValueError(f"out-of-scope source: {entry['source']}") from exc
    if target.parent not in allowed:
        raise ValueError(f"out-of-scope target: {entry['target']}")
    if not (target.exists() or target.is_symlink()):
        return None
    mode = entry["mode"]
    if mode in {"junction", "symlink"}:
        try:
            matches = os.path.samefile(target, source)
        except OSError:
            matches = False
    elif mode == "copy":
        matches = target.is_dir() and tree_digest(target) == entry["digest"]
    else:
        raise ValueError(f"unknown mirror mode: {mode}")
    if not matches:
        raise ValueError(f"modified runtime path: {entry['target']}")
    return target, mode


def known_sync_script(path: Path) -> bool:
    if not path.exists():
        return False
    content = path.read_text(encoding="utf-8")
    return all(
        marker in content
        for marker in (
            "Generate runtime skill mirrors from canonical root skills/.",
            "runtime-skill-mirrors.json",
            "DEFAULT_TARGETS",
        )
    )


def migrated_agents_md(content: str) -> str:
    replacements = (
        (
            "- Treat root `skills/` as the canonical project skill source.",
            (
                "- Treat root `skills/` as the canonical Skill authoring source.\n"
                "- Do not register or mirror it into runtime Skill directories during normal editing."
            ),
        ),
        (
            (
                "- Treat `.claude/skills/`, `.agents/skills/`, `.codebuddy/skills/`, and\n"
                "  `.workbuddy/skills/` as generated output.\n"
            ),
            "",
        ),
        ("- Do not hand-edit generated runtime mirrors.\n", ""),
        (
            (
                "- After changing canonical skills, run\n"
                "  `python scripts/agent-skills/sync_runtime_skills.py` and then its `--check` mode.\n"
            ),
            "",
        ),
    )
    normalized = content.replace("\r\n", "\n")
    for old, new in replacements:
        normalized = normalized.replace(old, new)
    normalized = normalized.replace(
        "after changing canonical skills or runtime\nmirrors.", "after changing canonical skills."
    ).replace("after changing canonical skills or runtime mirrors.", "after changing canonical skills.")
    lines = normalized.splitlines()
    kept = []
    skip_continuation = False
    for line in lines:
        if line.strip().startswith("- Kimi Code and OpenCode reuse `.agents/skills/`"):
            skip_continuation = True
            continue
        if skip_continuation and line.startswith(("  ", "\t")):
            continue
        skip_continuation = False
        kept.append(line)
    return "\n".join(kept).rstrip() + "\n"


def migrated_gitignore(content: str) -> str:
    normalized = content.replace("\r\n", "\n")
    if BEGIN not in normalized or END not in normalized:
        return content
    before, managed = normalized.split(BEGIN, 1)
    block, after = managed.split(END, 1)
    retained = [line for line in block.splitlines() if line.strip() not in LEGACY_IGNORES]
    retained = [line for line in retained if line.strip()]
    replacement = ""
    if retained:
        replacement = "\n".join([BEGIN, *retained, END])
    pieces = [piece.strip("\n") for piece in (before, replacement, after) if piece.strip("\n")]
    return "\n\n".join(pieces) + ("\n" if pieces else "")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo")
    parser.add_argument("--apply", action="store_true", help="apply the previewed cleanup")
    args = parser.parse_args()
    repo = Path(args.repo).expanduser().resolve()
    if not repo.is_dir():
        raise SystemExit(f"repo does not exist: {repo}")

    try:
        targets = [target for entry in load_entries(repo) if (target := owned_target(repo, entry))]
        sync = repo / SYNC_SCRIPT
        if sync.exists() and not known_sync_script(sync):
            raise ValueError("sync script is modified or user-owned")
    except ValueError as exc:
        print(f"Migration stopped; preserved existing files: {exc}", file=sys.stderr)
        return 1

    updates = []
    for relative, migrate in ((Path("AGENTS.md"), migrated_agents_md), (Path(".gitignore"), migrated_gitignore)):
        path = repo / relative
        if path.is_file():
            current = path.read_text(encoding="utf-8")
            updated = migrate(current)
            if updated != current:
                updates.append((path, updated))

    action = "remove" if args.apply else "would remove"
    for path, _ in targets:
        print(f"{action} {path.relative_to(repo)}")
    if sync.exists():
        print(f"{action} {SYNC_SCRIPT}")
    if (repo / MANIFEST).exists():
        print(f"{action} {MANIFEST}")
    for path, _ in updates:
        print(f"{'update' if args.apply else 'would update'} {path.relative_to(repo)}")

    if not args.apply:
        if not targets and not sync.exists() and not (repo / MANIFEST).exists() and not updates:
            print("No legacy generated runtime Skill infrastructure found.")
        print("Preview complete; rerun with --apply.")
        return 0

    for path, mode in targets:
        if path.is_symlink():
            path.unlink()
        elif mode == "junction":
            os.rmdir(path)
        else:
            shutil.rmtree(path)
    if sync.exists():
        sync.unlink()
    if (repo / MANIFEST).exists():
        (repo / MANIFEST).unlink()
    for path, content in updates:
        path.write_text(content, encoding="utf-8")
    for relative in (*RUNTIME_ROOTS, MANIFEST.parent, SYNC_SCRIPT.parent):
        path = repo / relative
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()
    print("Migration complete; canonical skills/ was preserved.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
