#!/usr/bin/env python3
"""Generate Claude, Codex, and CodeBuddy subagents from agents/registry.yaml."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: install it before running agents/sync_agents.py")


REPO = Path(__file__).resolve().parents[1]
REGISTRY = REPO / "agents" / "registry.yaml"
SKILLS_ROOT = REPO / "skills"
CLAUDE_DIR = REPO / ".claude" / "agents"
CODEX_DIR = REPO / ".codex" / "agents"
CODEBUDDY_DIR = REPO / ".codebuddy" / "agents"
INDEX = REPO / "agents" / "INDEX.md"
NOTICE = "Generated by agents/sync_agents.py from agents/registry.yaml; do not edit by hand."
REQUIRED = ("id", "kind", "description", "spec", "tier", "role_note", "output", "iron_rule")
ID_RE = re.compile(r"^(?=.{1,64}$)[a-z0-9]+(?:-[a-z0-9]+)*$")
CODEBUDDY_EFFORTS = {"minimal", "low", "medium", "high", "xhigh", "max"}


def display(path: Path) -> str:
    try:
        return path.relative_to(REPO).as_posix()
    except ValueError:
        return str(path)


def fail(message: str) -> None:
    raise SystemExit(f"registry error: {message}")


def validate_spec(value: str, agent_id: str) -> str:
    candidate = (REPO / value).resolve()
    try:
        relative = candidate.relative_to(SKILLS_ROOT.resolve())
    except ValueError:
        fail(f"spec for {agent_id} must stay under skills/: {value}")
    if "references" not in relative.parts or not value.endswith(("-agent.md", "-prompt.md")):
        fail(f"spec for {agent_id} must be a skill-owned references/*-agent.md or *-prompt.md file")
    owner = candidate.parent
    while owner != SKILLS_ROOT and not (owner / "SKILL.md").is_file():
        owner = owner.parent
    if owner == SKILLS_ROOT or not candidate.is_file():
        fail(f"missing skill-owned spec {value} for {agent_id}")
    return candidate.relative_to(REPO).as_posix()


def load_registry() -> tuple[dict, list[dict]]:
    try:
        data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as exc:
        fail(f"cannot read {display(REGISTRY)}: {exc}")
    if not isinstance(data, dict):
        fail("registry root must be a mapping")
    tiers = data.get("model_tiers", {})
    agents = data.get("agents", [])
    if not isinstance(tiers, dict) or not tiers:
        fail("model_tiers must be a non-empty mapping")
    if not isinstance(agents, list):
        fail("agents must be a list")

    seen: set[str] = set()
    normalized: list[dict] = []
    for raw in agents:
        if not isinstance(raw, dict):
            fail("every agents entry must be a mapping")
        missing = [key for key in REQUIRED if not raw.get(key)]
        if missing:
            fail(f"agent {raw.get('id', '?')} missing {missing}")
        agent = dict(raw)
        agent_id = str(agent["id"])
        if not ID_RE.fullmatch(agent_id):
            fail(f"invalid kebab-case id {agent_id}")
        if agent_id in seen:
            fail(f"duplicate id {agent_id}")
        seen.add(agent_id)
        tier_name = str(agent["tier"])
        if tier_name not in tiers or not isinstance(tiers[tier_name], dict):
            fail(f"unknown tier {tier_name} for {agent_id}")
        if agent.get("tools") is not None and not isinstance(agent["tools"], list):
            fail(f"tools must be a list for {agent_id}")
        if agent.get("codebuddy_tools") is not None and not isinstance(agent["codebuddy_tools"], list):
            fail(f"codebuddy_tools must be a list for {agent_id}")
        agent["spec"] = validate_spec(str(agent["spec"]), agent_id)
        tier = tiers[tier_name]
        agent["_claude_model"] = str(tier.get("claude", "sonnet"))
        agent["_codex_model"] = str(tier.get("codex", "gpt-5"))
        agent["_codex_reasoning_effort"] = str(tier.get("codex_reasoning_effort", "low"))
        agent["_codebuddy_model"] = str(tier.get("codebuddy", "inherit"))
        agent["_codebuddy_effort"] = str(tier.get("codebuddy_effort", ""))
        if agent["_codebuddy_effort"] and agent["_codebuddy_effort"] not in CODEBUDDY_EFFORTS:
            fail(f"invalid codebuddy_effort {agent['_codebuddy_effort']} for {agent_id}")
        normalized.append(agent)
    return tiers, normalized


def body(agent: dict) -> str:
    return (
        f"{str(agent['role_note']).strip()}\n\n"
        f"1. Read `{agent['spec']}` in full and follow it exactly.\n"
        "2. Read only the inputs the caller provides.\n"
        "3. Follow the spec output format and red lines.\n"
        f"4. {str(agent['output']).strip()}\n\n"
        f"Iron rule: {str(agent['iron_rule']).strip()}"
    )


def render_claude(agent: dict) -> str:
    tools = ", ".join(str(tool) for tool in agent.get("tools", []))
    lines = [f"name: {agent['id']}", f"description: {str(agent['description']).strip()}"]
    if tools:
        lines.append(f"tools: {tools}")
    lines.append(f"model: {agent['_claude_model']}")
    return "---\n" + "\n".join(lines) + "\n---\n" + f"<!-- {NOTICE} -->\n\n" + body(agent) + "\n"


def render_codex(agent: dict) -> str:
    description = str(agent["description"]).strip().replace("\\", "\\\\").replace('"', '\\"')
    rendered_body = body(agent)
    if '"""' in rendered_body:
        fail(f"agent {agent['id']} body contains triple quotes")
    lines = [
        f"# {NOTICE}",
        f'name = "{agent["id"]}"',
        f'description = "{description}"',
        f'model = "{agent["_codex_model"]}"',
        f'model_reasoning_effort = "{agent["_codex_reasoning_effort"]}"',
    ]
    if agent.get("sandbox"):
        lines.append(f'sandbox_mode = "{agent["sandbox"]}"')
    lines.append('developer_instructions = """\n' + rendered_body + '\n"""')
    return "\n".join(lines) + "\n"


def render_codebuddy(agent: dict) -> str:
    tools = agent.get("codebuddy_tools", agent.get("tools", []))
    description = json.dumps(str(agent["description"]).strip(), ensure_ascii=False)
    model = json.dumps(agent["_codebuddy_model"], ensure_ascii=False)
    lines = [f"name: {agent['id']}", f"description: {description}"]
    if tools:
        lines.append("tools: " + ", ".join(str(tool) for tool in tools))
    lines.append(f"model: {model}")
    if agent["_codebuddy_effort"]:
        lines.append(f"effort: {agent['_codebuddy_effort']}")
    return "---\n" + "\n".join(lines) + "\n---\n" + f"<!-- {NOTICE} -->\n\n" + body(agent) + "\n"


def render_index(agents: list[dict]) -> str:
    rows = [
        "# Subagent Index (generated)",
        "",
        f"<!-- {NOTICE} -->",
        "",
        "| Agent | Kind | Tier | Spec | Dispatched by |",
        "|---|---|---|---|---|",
    ]
    for agent in agents:
        rows.append(
            f"| `{agent['id']}` | {agent['kind']} | {agent['tier']} | "
            f"`{agent['spec']}` | {agent.get('dispatched_by', '-')} |"
        )
    return "\n".join(rows) + "\n"


def planned(agents: list[dict]) -> dict[Path, str]:
    files = {INDEX: render_index(agents)}
    for agent in agents:
        files[CLAUDE_DIR / f"{agent['id']}.md"] = render_claude(agent)
        files[CODEX_DIR / f"{agent['id']}.toml"] = render_codex(agent)
        files[CODEBUDDY_DIR / f"{agent['id']}.md"] = render_codebuddy(agent)
    return files


def is_generated(path: Path) -> bool:
    try:
        return NOTICE in path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False


def generated_orphans(files: dict[Path, str]) -> list[Path]:
    candidates = (
        list(CLAUDE_DIR.glob("*.md"))
        + list(CODEX_DIR.glob("*.toml"))
        + list(CODEBUDDY_DIR.glob("*.md"))
    )
    if INDEX.exists():
        candidates.append(INDEX)
    return sorted(path for path in candidates if path not in files and is_generated(path))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Synchronize generated Claude, Codex, and CodeBuddy subagents."
    )
    parser.add_argument("--check", action="store_true", help="verify without changing files")
    parser.add_argument("--replace-existing", action="store_true", help="replace conflicting user-owned files")
    args = parser.parse_args()

    _, agents = load_registry()
    files = planned(agents)
    stale = [path for path, content in files.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    orphans = generated_orphans(files)
    if args.check:
        problems = [f"{display(path)} (missing or changed)" for path in stale]
        problems.extend(f"{display(path)} (generated orphan)" for path in orphans)
        if problems:
            print("Out of sync:\n  " + "\n  ".join(problems))
            return 1
        print(f"In sync: {len(agents)} agents.")
        return 0

    for path in stale:
        if path.exists() and not is_generated(path) and not args.replace_existing:
            raise SystemExit(
                f"{display(path)} exists and is not generated; rerun with --replace-existing "
                "after preserving it"
            )
    for path in orphans:
        path.unlink()
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and path.is_dir():
            shutil.rmtree(path)
        path.write_text(content, encoding="utf-8")
    print(f"Generated {len(agents)} agents; removed {len(orphans)} generated orphan(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
